### ISSUE TITLE
Registry returned 404

### ISSUE THREAD

**Issue by gerfigna** [samuelagm/nativescript-xmpp-client#1] opened 2017-06-08 12:13 UTC
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nativescript-dev-nativescript-xmpp-client" "--save-dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/nativescript-dev-nativescript-xmpp-client
npm ERR! 404
npm ERR! 404  'nativescript-dev-nativescript-xmpp-client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gfigna/Documents/Peposa/Peposa/app/peposa/npm-debug.log
Command npm failed with exit code 1

**Comment by samuelagm** [comment] 2017-06-08 13:38
The name of the npm package is nativescript-xmpp-client  and not nativescript-dev-nativescript-xmpp-client. So try doing tns install nativescript-xmpp-client.

**Comment by gerfigna** [comment] 2017-06-08 14:31
I'm doing tns install nativescript-xmpp-client and the error returned is 
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/nativescript-dev-nativescript-xmpp-client

The demo app also is broken

**Comment by samuelagm** [comment] 2017-06-08 15:47
OK, this looks serious, I'll fix this ASAP. Thanks

**Comment by soulfly** [comment] 2017-12-13 10:36
The same on my side. Is there any fix?

**Comment by samuelagm** [comment] 2019-03-20 00:32
I've been unable to reproduce this error and I'll be closing this issue soon

**Closed** 2019-03-26 09:46 UTC
Labels: bug
